version: "3.7"

services:
  app: 
    build:
      context: "."
    image: building_access
    volumes:
      - database:/app/files
    ports:
      - 8000:8000
    restart: always

volumes:
  database: